server:
  port: 8080

spring:
  application:
    name: ms-pedidos360-bff
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/5aeb0fb8-efa9-497b-aa26-9cb8046ad6f0/v2.0